### ISSUE TITLE
Update Repository

### ISSUE THREAD

**Issue by victorborrasdev** [LittaPanda/vue-testing-handbook#29]
Hey @LittaPanda! I've seen this fork is more than 80 commits behind the original repo. Could you please update it regularly so I can translate the current content?

**Comment by LittaPanda** [comment]
Hi @vborras, of course I can... Sorry for the delay. I'm facing some issues nowadays, but yes... I'll do this as soon as I can.
Thanks a lot for your help.

**Comment by LittaPanda** [comment]
Done. Regards!
